apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app
  labels:
    name: jenkins-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkins-app
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: jenkins-app
    spec:
      containers:
      - name: test
        image: gcr.io/searce-academy/rohan-ci-cd/jenkinsapp
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-app
spec:
  selector:
    name: jenkins-app
  ports:
    - name: port1
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jenkins-app
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: jenkins-app
  targetCPUUtilizationPercentage: 80
